name: automation_with_emulator - 2
# on push we will trigger our code
on:
    workflow_dispatch:
    push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 #checkout the code
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install appium
        run: npm install -g appium

      - name: Check appium installation
        run: appium -v

      - name: Install appium automator
        run: appium driver install uiautomator2

      - name: Update  appium automator
        run: appium driver update uiautomator2

      - name: Start appium
        run: appium server --address 127.0.0.1 --port 4723 --use-drivers uiautomator2 --base-path /wd/hub &

      - name: Wait for Appium to start
        run: sleep 60 # Adjust the time as needed

      - name: Print Appium status
        run: curl http://127.0.0.1:4723/wd/hub/status

      - name: Run Ui Tests
        uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: 33
          target: google_apis
          arch: arm64-v8a
          avd-name: Pixel_6_API_33
          disable-animations: true
          script: /bin/true

      - name: Wait for emulator to boot
        run: |
         adb wait-for-device
         adb shell input keyevent 82
         adb devices
         echo "TEST2"
         sleep 30
        timeout-minutes: 5



      - name: Run tests
        run: ./gradlew connectedAndroidTest
      - name: Produce report
        run: mvn serenity:aggregate

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: test-screenshots
          path: artifacts/screenshots

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: target/site
