name: Ui Workflow
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Install appium
        run: npm install -g appium

      - name: Check appium installation
        run: appium -v

      - name: Install appium automator
        run: appium driver install uiautomator2

      - name: Update appium automator
        run: appium driver update uiautomator2

      - name: Start appium
        run: appium server --address 127.0.0.1 --port 4723 --use-drivers uiautomator2 --allow-insecure adb_shell &

      - name: Wait for Appium to start
        run: |
          for i in `seq 1 30`; do
            if curl -s http://127.0.0.1:4723/status | grep -q '"state":"success"'; then
              echo "Appium is up and running"
              break
            fi
            echo "Waiting for Appium to start..."
            sleep 2
          done

      - name: Print Appium status
        run: curl http://127.0.0.1:4723/status

      - name: Run UI Tests
        run: |
          adb devices # Ensure your device is connected and recognized
          mvn verify --file pom.xml \
            -Dappium.hub=http://127.0.0.1:4723 \
            -Dwebdriver.driver=appium \
            -Dappium.platformName=Android \
            -Dappium.deviceName="POCO X5 Pro" \
            -Dappium.udid=58d5b98 \
            -Dcucumber.filter.tags='@automated and @ANDROID'

      - name: Produce report
        run: mvn serenity:aggregate

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: test-screenshots
          path: artifacts/screenshots

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: target/site
