name: Java CI with Maven

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ref: referenceApp

#      - name: Checkout eudi-lib-ios-openid4vci-swift repository
#        uses: actions/checkout@v3
#        with:
#          repository: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-siop-openid4vp-swift.git
#          path: eudi-lib-ios-openid4vci-swift

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Scenario 1
        run: |
          #!/bin/bash
          mvn clean verify -Dcucumber.filter.tags="@WEB and @SCENARIO_01" $*
          mvn serenity:aggregate

      - name: Scenario 2
        run: |
         #!/bin/bash
         mvn clean verify -Dcucumber.filter.tags="@WEB and @SCENARIO_02" $*
         mvn serenity:aggregate

#      - name: Scenario 3
#        run: |
#         #!/bin/bash
#         mvn clean verify -Dcucumber.filter.tags="@WEB and @SCENARIO_03" $*
#         mvn serenity:aggregate