name: Manual Workflow
on:
  workflow_dispatch:
  #[push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: milestone/2025.Q1

      - name: Permission to file .sh
        run: |
          #!/bin/bash
          sudo chmod +x local-execution.sh

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS 18.16.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Compile ReadmeManager.java
        run: javac -d out src/test/java/eu/europa/eudi/utils/factory/ReadmeManager.java

      - name: Run ReadmeManager
        run: java -cp out src/test/java/eu/europa/eudi/utils/factory/ReadmeManager.java

      - name: Clean old reports
        run: |
          mvn clean
          rm -rf target/site

      - name: Clean Maven cache
        run: mvn dependency:purge-local-repository -DreResolve=false

      - name: Run Ui Tests
        run: |
          #!/bin/bash
          mvn clean verify -Dcucumber.filter.tags="@Q1_2025 and @ANDROID" "$@"
          rm -rf target/site/serenity
          mvn serenity:aggregate -Dtags=Q1_2025

      - name: Produce report
        run: mvn serenity:aggregate -Dtags=Q1_2025

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/site

      - name: Compile ReadmeManager.java
        run: javac -d out src/test/java/eu/europa/eudi/utils/factory/ReadmeManager.java

      - name: Run ReadmeManager
        run: java -cp out src/test/java/eu/europa/eudi/utils/factory/ReadmeManager.java