name: Manual Workflow
on: [push]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: milestone/2024.Q4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS 18.16.1
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      # - name: Run Ui Tests
      #   run: |
      #    #!/bin/bash
      #    mvn clean verify -Dcucumber.filter.tags="@manual"

      - name: Run ReadmeManager
        run: |
          #!/bin/bash
          ./path/to/ReadmeManager # Adjust the path to where ReadmeManager is located

      - name: Produce report
        run: mvn serenity:aggregate

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: target/site
